// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: keyvalue.proto

#include "keyvalue.pb.h"
#include "keyvalue.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace keyvaluestore {

static const char* KeyValueStore_method_names[] = {
  "/keyvaluestore.KeyValueStore/GetValues",
  "/keyvaluestore.KeyValueStore/PutValues",
  "/keyvaluestore.KeyValueStore/DelValue",
};

std::unique_ptr< KeyValueStore::Stub> KeyValueStore::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KeyValueStore::Stub> stub(new KeyValueStore::Stub(channel, options));
  return stub;
}

KeyValueStore::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetValues_(KeyValueStore_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PutValues_(KeyValueStore_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DelValue_(KeyValueStore_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KeyValueStore::Stub::GetValues(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::keyvaluestore::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetValues_, context, request, response);
}

void KeyValueStore::Stub::async::GetValues(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, std::move(f));
}

void KeyValueStore::Stub::async::GetValues(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::PrepareAsyncGetValuesRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::keyvaluestore::Response, ::keyvaluestore::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetValues_, context, request);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::AsyncGetValuesRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetValuesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KeyValueStore::Stub::PutValues(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::keyvaluestore::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PutValues_, context, request, response);
}

void KeyValueStore::Stub::async::PutValues(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutValues_, context, request, response, std::move(f));
}

void KeyValueStore::Stub::async::PutValues(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutValues_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::PrepareAsyncPutValuesRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::keyvaluestore::Response, ::keyvaluestore::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PutValues_, context, request);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::AsyncPutValuesRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutValuesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KeyValueStore::Stub::DelValue(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::keyvaluestore::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DelValue_, context, request, response);
}

void KeyValueStore::Stub::async::DelValue(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelValue_, context, request, response, std::move(f));
}

void KeyValueStore::Stub::async::DelValue(::grpc::ClientContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::PrepareAsyncDelValueRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::keyvaluestore::Response, ::keyvaluestore::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DelValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::keyvaluestore::Response>* KeyValueStore::Stub::AsyncDelValueRaw(::grpc::ClientContext* context, const ::keyvaluestore::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

KeyValueStore::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeyValueStore::Service, ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::keyvaluestore::Request* req,
             ::keyvaluestore::Response* resp) {
               return service->GetValues(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeyValueStore::Service, ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::keyvaluestore::Request* req,
             ::keyvaluestore::Response* resp) {
               return service->PutValues(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeyValueStore::Service, ::keyvaluestore::Request, ::keyvaluestore::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::keyvaluestore::Request* req,
             ::keyvaluestore::Response* resp) {
               return service->DelValue(ctx, req, resp);
             }, this)));
}

KeyValueStore::Service::~Service() {
}

::grpc::Status KeyValueStore::Service::GetValues(::grpc::ServerContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KeyValueStore::Service::PutValues(::grpc::ServerContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KeyValueStore::Service::DelValue(::grpc::ServerContext* context, const ::keyvaluestore::Request* request, ::keyvaluestore::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace keyvaluestore

